import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const emailTemplates = [
  // Authentication
  { templateKey: 'welcome_email', templateName: 'Welcome Email', category: 'Authentication', subject: 'Welcome to Thozhil Koodam — {{company_name}}', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h1 style="color:#7c3aed">Welcome, {{candidate_name}}!</h1><p>Your account has been created successfully.</p><p>Login: <a href="{{login_url}}">{{login_url}}</a></p><p>Email: {{email}}</p></div>', variables: '["candidate_name","company_name","email","login_url"]' },
  { templateKey: 'email_verification', templateName: 'Email Verification', category: 'Authentication', subject: 'Verify your email address', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Verify Your Email</h2><p>Click the link below to verify your email:</p><p><a href="{{verification_link}}" style="display:inline-block;padding:12px 24px;background:#7c3aed;color:#fff;text-decoration:none;border-radius:6px">Verify Email</a></p><p>Or copy: {{verification_link}}</p></div>', variables: '["candidate_name","email","verification_link"]' },
  { templateKey: 'password_reset', templateName: 'Password Reset', category: 'Authentication', subject: 'Reset your password', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Reset Password</h2><p>Click below to reset your password:</p><p><a href="{{reset_link}}" style="display:inline-block;padding:12px 24px;background:#7c3aed;color:#fff;text-decoration:none;border-radius:6px">Reset Password</a></p><p>This link expires in 1 hour.</p></div>', variables: '["candidate_name","email","reset_link"]' },
  { templateKey: 'login_alert', templateName: 'Login Alert', category: 'Authentication', subject: 'New login to your account', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">New Login Detected</h2><p>Hi {{candidate_name}},</p><p>A new login was detected on your account.</p><p>If this was you, you can ignore this email. If not, please change your password immediately.</p></div>', variables: '["candidate_name","email","date","time"]' },
  // Recruitment
  { templateKey: 'job_posted_success', templateName: 'Job Posted Successfully', category: 'Recruitment', subject: 'Job posted: {{job_title}}', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Job Posted Successfully</h2><p>Dear {{recruiter_name}},</p><p>Your job <strong>{{job_title}}</strong> has been posted successfully and is pending admin review.</p><p>You will be notified once it is approved.</p></div>', variables: '["recruiter_name","company_name","job_title","date"]' },
  { templateKey: 'job_approved', templateName: 'Job Approved', category: 'Recruitment', subject: 'Job approved: {{job_title}}', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Job Approved</h2><p>Dear {{recruiter_name}},</p><p>Your job posting <strong>{{job_title}}</strong> has been approved and is now live.</p><p>Candidates can now apply.</p></div>', variables: '["recruiter_name","company_name","job_title","date"]' },
  { templateKey: 'job_rejected', templateName: 'Job Rejected', category: 'Recruitment', subject: 'Job posting update: {{job_title}}', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#dc2626">Job Posting Update</h2><p>Dear {{recruiter_name}},</p><p>Your job posting <strong>{{job_title}}</strong> has been reviewed and was not approved at this time.</p><p>Please review the feedback and resubmit if needed.</p></div>', variables: '["recruiter_name","company_name","job_title","date"]' },
  { templateKey: 'candidate_applied', templateName: 'Candidate Applied', category: 'Recruitment', subject: 'New application for {{job_title}}', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">New Application Received</h2><p>Dear {{recruiter_name}},</p><p><strong>{{candidate_name}}</strong> has applied for <strong>{{job_title}}</strong>.</p><p>Login to review the application.</p></div>', variables: '["recruiter_name","candidate_name","job_title","company_name","date"]' },
  { templateKey: 'interview_scheduled', templateName: 'Interview Scheduled', category: 'Recruitment', subject: 'Interview scheduled for {{job_title}}', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Interview Scheduled</h2><p>Dear {{candidate_name}},</p><p>Your interview for <strong>{{job_title}}</strong> at <strong>{{company_name}}</strong> has been scheduled.</p><p><strong>Date:</strong> {{date}}<br><strong>Time:</strong> {{time}}</p><p><strong>Meeting Link:</strong> <a href="{{meeting_link}}">{{meeting_link}}</a></p></div>', variables: '["candidate_name","job_title","company_name","date","time","meeting_link"]' },
  { templateKey: 'interview_reminder', templateName: 'Interview Reminder', category: 'Recruitment', subject: 'Reminder: Interview for {{job_title}} tomorrow', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Interview Reminder</h2><p>Dear {{candidate_name}},</p><p>This is a reminder for your interview tomorrow.</p><p><strong>Position:</strong> {{job_title}}<br><strong>Company:</strong> {{company_name}}<br><strong>Date:</strong> {{date}}<br><strong>Time:</strong> {{time}}</p><p><strong>Meeting Link:</strong> <a href="{{meeting_link}}">{{meeting_link}}</a></p></div>', variables: '["candidate_name","job_title","company_name","date","time","meeting_link"]' },
  { templateKey: 'offer_letter', templateName: 'Offer Letter', category: 'Recruitment', subject: 'Offer letter for {{job_title}}', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Congratulations {{candidate_name}}!</h2><p>We are pleased to offer you the position of <strong>{{job_title}}</strong> at <strong>{{company_name}}</strong>.</p><p>Please review the attached offer letter for details including compensation, start date, and terms.</p><p>We look forward to having you on the team!</p></div>', variables: '["candidate_name","job_title","company_name","date"]' },
  // Business
  { templateKey: 'agency_registration_received', templateName: 'Recruitment Agency Registration Received', category: 'Business', subject: 'Registration received — {{agency_name}}', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Registration Received</h2><p>Dear {{agency_name}},</p><p>Your registration has been received and is pending review.</p><p>We will notify you once your account is approved.</p></div>', variables: '["agency_name","email","date"]' },
  { templateKey: 'agency_approved', templateName: 'Recruitment Agency Approved', category: 'Business', subject: 'Your agency has been approved', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Agency Approved</h2><p>Dear {{agency_name}},</p><p>Your recruitment agency has been approved. You can now log in and start posting jobs.</p><p><a href="{{login_url}}" style="display:inline-block;padding:12px 24px;background:#7c3aed;color:#fff;text-decoration:none;border-radius:6px">Login Now</a></p></div>', variables: '["agency_name","email","login_url","date"]' },
  { templateKey: 'agency_rejected', templateName: 'Recruitment Agency Rejected', category: 'Business', subject: 'Agency registration status', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#dc2626">Registration Update</h2><p>Dear {{agency_name}},</p><p>Your agency registration has been reviewed and was not approved at this time.</p><p>Please contact support for more information.</p></div>', variables: '["agency_name","email","support_email"]' },
  { templateKey: 'hr_recruiter_account_created', templateName: 'HR Recruiter Account Created', category: 'Business', subject: 'Your HR Recruiter account has been created', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Account Created</h2><p>Dear {{recruiter_name}},</p><p>Your HR Recruiter account has been created.</p><p><strong>Employee ID:</strong> {{employee_id}}<br><strong>Email:</strong> {{email}}</p><p><a href="{{login_url}}" style="display:inline-block;padding:12px 24px;background:#7c3aed;color:#fff;text-decoration:none;border-radius:6px">Login Now</a></p></div>', variables: '["recruiter_name","employee_id","email","login_url"]' },
  { templateKey: 'msme_registration_received', templateName: 'MSME Registration Received', category: 'Business', subject: 'MSME registration received', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">MSME Registration Received</h2><p>Dear {{company_name}},</p><p>Your MSME registration has been received and is pending review.</p></div>', variables: '["company_name","email","date"]' },
  { templateKey: 'msme_approved', templateName: 'MSME Approved', category: 'Business', subject: 'MSME account approved', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">MSME Account Approved</h2><p>Dear {{company_name}},</p><p>Your MSME account has been approved.</p><p><a href="{{login_url}}" style="display:inline-block;padding:12px 24px;background:#7c3aed;color:#fff;text-decoration:none;border-radius:6px">Login Now</a></p></div>', variables: '["company_name","email","login_url"]' },
  { templateKey: 'msme_requirement_received', templateName: 'MSME Requirement Received', category: 'Business', subject: 'New requirement received', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Requirement Received</h2><p>Dear {{company_name}},</p><p>Your requirement for <strong>{{job_title}}</strong> has been received and will be processed shortly.</p></div>', variables: '["company_name","job_title","date"]' },
  // Billing
  { templateKey: 'payment_successful', templateName: 'Payment Successful', category: 'Billing', subject: 'Payment confirmed — {{plan}}', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Payment Successful</h2><p>Dear {{company_name}},</p><p>Your payment of <strong>{{amount}}</strong> for the <strong>{{plan}}</strong> plan has been received.</p><p>Invoice: {{invoice_number}}</p></div>', variables: '["company_name","amount","plan","invoice_number","date"]' },
  { templateKey: 'payment_failed', templateName: 'Payment Failed', category: 'Billing', subject: 'Payment failed', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#dc2626">Payment Failed</h2><p>Dear {{company_name}},</p><p>Your payment of <strong>{{amount}}</strong> could not be processed.</p><p>Please update your payment method and try again.</p></div>', variables: '["company_name","amount","plan","date"]' },
  { templateKey: 'invoice', templateName: 'Invoice', category: 'Billing', subject: 'Invoice {{invoice_number}} from Thozhil Koodam', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Invoice</h2><p>Dear {{company_name}},</p><p>Please find your invoice below:</p><p><strong>Invoice:</strong> {{invoice_number}}<br><strong>Plan:</strong> {{plan}}<br><strong>Amount:</strong> {{amount}}<br><strong>Date:</strong> {{date}}</p></div>', variables: '["company_name","invoice_number","plan","amount","date"]' },
  { templateKey: 'subscription_activated', templateName: 'Subscription Activated', category: 'Billing', subject: 'Subscription activated — {{plan}}', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Subscription Activated</h2><p>Dear {{company_name}},</p><p>Your <strong>{{plan}}</strong> subscription is now active.</p><p>Thank you for choosing Thozhil Koodam!</p></div>', variables: '["company_name","plan","date"]' },
  { templateKey: 'subscription_expiring', templateName: 'Subscription Expiring', category: 'Billing', subject: 'Your subscription is expiring soon', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#f59e0b">Subscription Expiring Soon</h2><p>Dear {{company_name}},</p><p>Your <strong>{{plan}}</strong> subscription will expire soon.</p><p>Please renew to continue enjoying our services.</p></div>', variables: '["company_name","plan","date"]' },
  { templateKey: 'subscription_expired', templateName: 'Subscription Expired', category: 'Billing', subject: 'Subscription expired', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#dc2626">Subscription Expired</h2><p>Dear {{company_name}},</p><p>Your <strong>{{plan}}</strong> subscription has expired.</p><p>Renew now to reactivate your account features.</p></div>', variables: '["company_name","plan","date"]' },
  // Support
  { templateKey: 'contact_form_submitted', templateName: 'Contact Form Submitted', category: 'Support', subject: 'Thank you for contacting us', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Thank You</h2><p>Dear {{candidate_name}},</p><p>We have received your message and will get back to you within 24 hours.</p><p>For urgent inquiries, email us at {{support_email}}.</p></div>', variables: '["candidate_name","email","support_email"]' },
  { templateKey: 'support_ticket_created', templateName: 'Support Ticket Created', category: 'Support', subject: 'Support ticket received', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Support Ticket Created</h2><p>Dear {{candidate_name}},</p><p>Your support ticket has been created. Our team will review it shortly.</p></div>', variables: '["candidate_name","email","date"]' },
  { templateKey: 'ticket_closed', templateName: 'Ticket Closed', category: 'Support', subject: 'Your support ticket has been resolved', body: '<div style="font-family:Arial;max-width:600px;margin:0 auto;padding:24px"><h2 style="color:#7c3aed">Ticket Resolved</h2><p>Dear {{candidate_name}},</p><p>Your support ticket has been resolved. If you have further questions, please reply to this email.</p></div>', variables: '["candidate_name","email","support_email"]' },
]

const smsTemplates = [
  { templateKey: 'otp_verification', templateName: 'OTP Verification', category: 'Authentication', message: 'Your Thozhil Koodam verification OTP is {{otp}}. Valid for 10 minutes.', variables: '["otp"]' },
  { templateKey: 'password_reset_otp', templateName: 'Password Reset OTP', category: 'Authentication', message: 'Your password reset OTP is {{otp}}. Valid for 10 minutes.', variables: '["otp"]' },
  { templateKey: 'sms_job_approved', templateName: 'Job Approved', category: 'Recruitment', message: 'Hi {{name}}, your job posting "{{job_title}}" has been approved and is now live.', variables: '["name","job_title"]' },
  { templateKey: 'sms_candidate_applied', templateName: 'Candidate Applied', category: 'Recruitment', message: 'New application from {{name}} for {{job_title}}. Review on Thozhil Koodam.', variables: '["name","job_title"]' },
  { templateKey: 'sms_interview_reminder', templateName: 'Interview Reminder', category: 'Recruitment', message: 'Reminder: Your interview for {{job_title}} at {{company_name}} is on {{date}} at {{time}}.', variables: '["name","job_title","company_name","date","time"]' },
  { templateKey: 'sms_agency_approved', templateName: 'Agency Approved', category: 'Business', message: 'Your agency {{company_name}} has been approved. Login at {{login_url}}.', variables: '["company_name","login_url"]' },
  { templateKey: 'sms_msme_approved', templateName: 'MSME Approved', category: 'Business', message: 'Your MSME account {{company_name}} has been approved. Login at {{login_url}}.', variables: '["company_name","login_url"]' },
  { templateKey: 'sms_payment_successful', templateName: 'Payment Successful', category: 'Billing', message: 'Payment of {{amount}} for {{plan}} plan was successful. Thank you!', variables: '["amount","plan"]' },
  { templateKey: 'sms_subscription_expiry', templateName: 'Subscription Expiry Reminder', category: 'Billing', message: 'Your {{plan}} subscription expires soon. Renew now to avoid interruption.', variables: '["plan"]' },
]

async function seed() {
  console.log('Seeding email templates...')
  for (const t of emailTemplates) {
    await prisma.emailTemplate.upsert({
      where: { templateKey: t.templateKey },
      update: t,
      create: t,
    })
  }
  console.log(`${emailTemplates.length} email templates seeded.`)

  console.log('Seeding SMS templates...')
  for (const t of smsTemplates) {
    await prisma.smsTemplate.upsert({
      where: { templateKey: t.templateKey },
      update: t,
      create: t,
    })
  }
  console.log(`${smsTemplates.length} SMS templates seeded.`)

  await prisma.$disconnect()
  console.log('Done.')
}

seed().catch((e) => {
  console.error(e)
  prisma.$disconnect()
  process.exit(1)
})
