import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // ----- COUNTRY -----
  const country = await prisma.country.upsert({
    where: { id: 1 },
    update: { name: 'India', iso2: 'IN' },
    create: { id: 1, name: 'India', iso2: 'IN' },
  })
  console.log(`Seeded country: ${country.name}`)

  // ----- STATES & UNION TERRITORIES -----
  const statesData = [
    { id: 1, name: 'Andhra Pradesh' },
    { id: 2, name: 'Arunachal Pradesh' },
    { id: 3, name: 'Assam' },
    { id: 4, name: 'Bihar' },
    { id: 5, name: 'Chhattisgarh' },
    { id: 6, name: 'Goa' },
    { id: 7, name: 'Gujarat' },
    { id: 8, name: 'Haryana' },
    { id: 9, name: 'Himachal Pradesh' },
    { id: 10, name: 'Jharkhand' },
    { id: 11, name: 'Karnataka' },
    { id: 12, name: 'Kerala' },
    { id: 13, name: 'Madhya Pradesh' },
    { id: 14, name: 'Maharashtra' },
    { id: 15, name: 'Manipur' },
    { id: 16, name: 'Meghalaya' },
    { id: 17, name: 'Mizoram' },
    { id: 18, name: 'Nagaland' },
    { id: 19, name: 'Odisha' },
    { id: 20, name: 'Punjab' },
    { id: 21, name: 'Rajasthan' },
    { id: 22, name: 'Sikkim' },
    { id: 23, name: 'Tamil Nadu' },
    { id: 24, name: 'Telangana' },
    { id: 25, name: 'Tripura' },
    { id: 26, name: 'Uttar Pradesh' },
    { id: 27, name: 'Uttarakhand' },
    { id: 28, name: 'West Bengal' },
    { id: 29, name: 'Andaman and Nicobar Islands' },
    { id: 30, name: 'Chandigarh' },
    { id: 31, name: 'Dadra and Nagar Haveli and Daman and Diu' },
    { id: 32, name: 'Delhi' },
    { id: 33, name: 'Jammu and Kashmir' },
    { id: 34, name: 'Ladakh' },
    { id: 35, name: 'Lakshadweep' },
    { id: 36, name: 'Puducherry' },
  ]

  const stateIds: number[] = []
  for (const s of statesData) {
    const state = await prisma.state.upsert({
      where: { id: s.id },
      update: { name: s.name, countryId: country.id },
      create: { id: s.id, name: s.name, countryId: country.id },
    })
    stateIds.push(state.id)
  }
  console.log(`Seeded ${statesData.length} states/union territories`)

  // ----- DISTRICTS -----
  // Organized by state ID
  const districtsData: { id: number; name: string; stateId: number }[] = [
    // Andhra Pradesh (1)
    { id: 1, name: 'Anakapalli', stateId: 1 },
    { id: 2, name: 'Anantapur', stateId: 1 },
    { id: 3, name: 'Annamayya', stateId: 1 },
    { id: 4, name: 'Bapatla', stateId: 1 },
    { id: 5, name: 'Chittoor', stateId: 1 },
    { id: 6, name: 'East Godavari', stateId: 1 },
    { id: 7, name: 'Eluru', stateId: 1 },
    { id: 8, name: 'Guntur', stateId: 1 },
    { id: 9, name: 'Kakinada', stateId: 1 },
    { id: 10, name: 'Konaseema', stateId: 1 },
    { id: 11, name: 'Krishna', stateId: 1 },
    { id: 12, name: 'Kurnool', stateId: 1 },
    { id: 13, name: 'Nandyal', stateId: 1 },
    { id: 14, name: 'Nellore', stateId: 1 },
    { id: 15, name: 'Palnadu', stateId: 1 },
    { id: 16, name: 'Prakasam', stateId: 1 },
    { id: 17, name: 'Srikakulam', stateId: 1 },
    { id: 18, name: 'Sri Sathya Sai', stateId: 1 },
    { id: 19, name: 'Visakhapatnam', stateId: 1 },
    { id: 20, name: 'Vizianagaram', stateId: 1 },
    { id: 21, name: 'West Godavari', stateId: 1 },
    { id: 22, name: 'YSR Kadapa', stateId: 1 },

    // Arunachal Pradesh (2)
    { id: 23, name: 'Anjaw', stateId: 2 },
    { id: 24, name: 'Changlang', stateId: 2 },
    { id: 25, name: 'Dibang Valley', stateId: 2 },
    { id: 26, name: 'East Kameng', stateId: 2 },
    { id: 27, name: 'East Siang', stateId: 2 },
    { id: 28, name: 'Kamle', stateId: 2 },
    { id: 29, name: 'Kra Daadi', stateId: 2 },
    { id: 30, name: 'Kurung Kumey', stateId: 2 },
    { id: 31, name: 'Lepa Rada', stateId: 2 },
    { id: 32, name: 'Lohit', stateId: 2 },
    { id: 33, name: 'Longding', stateId: 2 },
    { id: 34, name: 'Lower Dibang Valley', stateId: 2 },
    { id: 35, name: 'Lower Siang', stateId: 2 },
    { id: 36, name: 'Lower Subansiri', stateId: 2 },
    { id: 37, name: 'Namsai', stateId: 2 },
    { id: 38, name: 'Pakke Kessang', stateId: 2 },
    { id: 39, name: 'Papum Pare', stateId: 2 },
    { id: 40, name: 'Shi Yomi', stateId: 2 },
    { id: 41, name: 'Siang', stateId: 2 },
    { id: 42, name: 'Tawang', stateId: 2 },
    { id: 43, name: 'Tirap', stateId: 2 },
    { id: 44, name: 'Upper Siang', stateId: 2 },
    { id: 45, name: 'Upper Subansiri', stateId: 2 },
    { id: 46, name: 'West Kameng', stateId: 2 },
    { id: 47, name: 'West Siang', stateId: 2 },
    { id: 48, name: 'Itanagar', stateId: 2 },

    // Assam (3)
    { id: 49, name: 'Baksa', stateId: 3 },
    { id: 50, name: 'Barpeta', stateId: 3 },
    { id: 51, name: 'Biswanath', stateId: 3 },
    { id: 52, name: 'Bongaigaon', stateId: 3 },
    { id: 53, name: 'Cachar', stateId: 3 },
    { id: 54, name: 'Charaideo', stateId: 3 },
    { id: 55, name: 'Chirang', stateId: 3 },
    { id: 56, name: 'Darrang', stateId: 3 },
    { id: 57, name: 'Dhemaji', stateId: 3 },
    { id: 58, name: 'Dhubri', stateId: 3 },
    { id: 59, name: 'Dibrugarh', stateId: 3 },
    { id: 60, name: 'Dima Hasao', stateId: 3 },
    { id: 61, name: 'Goalpara', stateId: 3 },
    { id: 62, name: 'Golaghat', stateId: 3 },
    { id: 63, name: 'Hailakandi', stateId: 3 },
    { id: 64, name: 'Hojai', stateId: 3 },
    { id: 65, name: 'Jorhat', stateId: 3 },
    { id: 66, name: 'Kamrup', stateId: 3 },
    { id: 67, name: 'Kamrup Metropolitan', stateId: 3 },
    { id: 68, name: 'Karbi Anglong', stateId: 3 },
    { id: 69, name: 'Karimganj', stateId: 3 },
    { id: 70, name: 'Kokrajhar', stateId: 3 },
    { id: 71, name: 'Lakhimpur', stateId: 3 },
    { id: 72, name: 'Majuli', stateId: 3 },
    { id: 73, name: 'Morigaon', stateId: 3 },
    { id: 74, name: 'Nagaon', stateId: 3 },
    { id: 75, name: 'Nalbari', stateId: 3 },
    { id: 76, name: 'Sivasagar', stateId: 3 },
    { id: 77, name: 'Sonitpur', stateId: 3 },
    { id: 78, name: 'South Salmara-Mankachar', stateId: 3 },
    { id: 79, name: 'Tinsukia', stateId: 3 },
    { id: 80, name: 'Udalguri', stateId: 3 },
    { id: 81, name: 'West Karbi Anglong', stateId: 3 },

    // Bihar (4)
    { id: 82, name: 'Araria', stateId: 4 },
    { id: 83, name: 'Arwal', stateId: 4 },
    { id: 84, name: 'Aurangabad', stateId: 4 },
    { id: 85, name: 'Banka', stateId: 4 },
    { id: 86, name: 'Begusarai', stateId: 4 },
    { id: 87, name: 'Bhagalpur', stateId: 4 },
    { id: 88, name: 'Bhojpur', stateId: 4 },
    { id: 89, name: 'Buxar', stateId: 4 },
    { id: 90, name: 'Darbhanga', stateId: 4 },
    { id: 91, name: 'East Champaran', stateId: 4 },
    { id: 92, name: 'Gaya', stateId: 4 },
    { id: 93, name: 'Gopalganj', stateId: 4 },
    { id: 94, name: 'Jamui', stateId: 4 },
    { id: 95, name: 'Jehanabad', stateId: 4 },
    { id: 96, name: 'Kaimur', stateId: 4 },
    { id: 97, name: 'Katihar', stateId: 4 },
    { id: 98, name: 'Khagaria', stateId: 4 },
    { id: 99, name: 'Kishanganj', stateId: 4 },
    { id: 100, name: 'Lakhisarai', stateId: 4 },
    { id: 101, name: 'Madhepura', stateId: 4 },
    { id: 102, name: 'Madhubani', stateId: 4 },
    { id: 103, name: 'Munger', stateId: 4 },
    { id: 104, name: 'Muzaffarpur', stateId: 4 },
    { id: 105, name: 'Nalanda', stateId: 4 },
    { id: 106, name: 'Nawada', stateId: 4 },
    { id: 107, name: 'Patna', stateId: 4 },
    { id: 108, name: 'Purnia', stateId: 4 },
    { id: 109, name: 'Rohtas', stateId: 4 },
    { id: 110, name: 'Saharsa', stateId: 4 },
    { id: 111, name: 'Samastipur', stateId: 4 },
    { id: 112, name: 'Saran', stateId: 4 },
    { id: 113, name: 'Sheikhpura', stateId: 4 },
    { id: 114, name: 'Sheohar', stateId: 4 },
    { id: 115, name: 'Sitamarhi', stateId: 4 },
    { id: 116, name: 'Siwan', stateId: 4 },
    { id: 117, name: 'Supaul', stateId: 4 },
    { id: 118, name: 'Vaishali', stateId: 4 },
    { id: 119, name: 'West Champaran', stateId: 4 },

    // Chhattisgarh (5)
    { id: 120, name: 'Balod', stateId: 5 },
    { id: 121, name: 'Baloda Bazar', stateId: 5 },
    { id: 122, name: 'Balrampur', stateId: 5 },
    { id: 123, name: 'Bastar', stateId: 5 },
    { id: 124, name: 'Bemetara', stateId: 5 },
    { id: 125, name: 'Bijapur', stateId: 5 },
    { id: 126, name: 'Bilaspur', stateId: 5 },
    { id: 127, name: 'Dantewada', stateId: 5 },
    { id: 128, name: 'Dhamtari', stateId: 5 },
    { id: 129, name: 'Durg', stateId: 5 },
    { id: 130, name: 'Gariaband', stateId: 5 },
    { id: 131, name: 'Gaurela-Pendra-Marwahi', stateId: 5 },
    { id: 132, name: 'Janjgir-Champa', stateId: 5 },
    { id: 133, name: 'Jashpur', stateId: 5 },
    { id: 134, name: 'Kabirdham', stateId: 5 },
    { id: 135, name: 'Kanker', stateId: 5 },
    { id: 136, name: 'Kondagaon', stateId: 5 },
    { id: 137, name: 'Korba', stateId: 5 },
    { id: 138, name: 'Koriya', stateId: 5 },
    { id: 139, name: 'Mahasamund', stateId: 5 },
    { id: 140, name: 'Mungeli', stateId: 5 },
    { id: 141, name: 'Narayanpur', stateId: 5 },
    { id: 142, name: 'Raigarh', stateId: 5 },
    { id: 143, name: 'Raipur', stateId: 5 },
    { id: 144, name: 'Rajnandgaon', stateId: 5 },
    { id: 145, name: 'Sukma', stateId: 5 },
    { id: 146, name: 'Surajpur', stateId: 5 },
    { id: 147, name: 'Surguja', stateId: 5 },

    // Goa (6)
    { id: 148, name: 'North Goa', stateId: 6 },
    { id: 149, name: 'South Goa', stateId: 6 },

    // Gujarat (7)
    { id: 150, name: 'Ahmedabad', stateId: 7 },
    { id: 151, name: 'Amreli', stateId: 7 },
    { id: 152, name: 'Anand', stateId: 7 },
    { id: 153, name: 'Aravalli', stateId: 7 },
    { id: 154, name: 'Banaskantha', stateId: 7 },
    { id: 155, name: 'Bharuch', stateId: 7 },
    { id: 156, name: 'Bhavnagar', stateId: 7 },
    { id: 157, name: 'Botad', stateId: 7 },
    { id: 158, name: 'Chhota Udaipur', stateId: 7 },
    { id: 159, name: 'Dahod', stateId: 7 },
    { id: 160, name: 'Dang', stateId: 7 },
    { id: 161, name: 'Devbhoomi Dwarka', stateId: 7 },
    { id: 162, name: 'Gandhinagar', stateId: 7 },
    { id: 163, name: 'Gir Somnath', stateId: 7 },
    { id: 164, name: 'Jamnagar', stateId: 7 },
    { id: 165, name: 'Junagadh', stateId: 7 },
    { id: 166, name: 'Kheda', stateId: 7 },
    { id: 167, name: 'Kutch', stateId: 7 },
    { id: 168, name: 'Mahisagar', stateId: 7 },
    { id: 169, name: 'Mehsana', stateId: 7 },
    { id: 170, name: 'Morbi', stateId: 7 },
    { id: 171, name: 'Narmada', stateId: 7 },
    { id: 172, name: 'Navsari', stateId: 7 },
    { id: 173, name: 'Panchmahal', stateId: 7 },
    { id: 174, name: 'Patan', stateId: 7 },
    { id: 175, name: 'Porbandar', stateId: 7 },
    { id: 176, name: 'Rajkot', stateId: 7 },
    { id: 177, name: 'Sabarkantha', stateId: 7 },
    { id: 178, name: 'Surat', stateId: 7 },
    { id: 179, name: 'Surendranagar', stateId: 7 },
    { id: 180, name: 'Tapi', stateId: 7 },
    { id: 181, name: 'Vadodara', stateId: 7 },
    { id: 182, name: 'Valsad', stateId: 7 },

    // Haryana (8)
    { id: 183, name: 'Ambala', stateId: 8 },
    { id: 184, name: 'Bhiwani', stateId: 8 },
    { id: 185, name: 'Charkhi Dadri', stateId: 8 },
    { id: 186, name: 'Faridabad', stateId: 8 },
    { id: 187, name: 'Fatehabad', stateId: 8 },
    { id: 188, name: 'Gurugram', stateId: 8 },
    { id: 189, name: 'Hisar', stateId: 8 },
    { id: 190, name: 'Jhajjar', stateId: 8 },
    { id: 191, name: 'Jind', stateId: 8 },
    { id: 192, name: 'Kaithal', stateId: 8 },
    { id: 193, name: 'Karnal', stateId: 8 },
    { id: 194, name: 'Kurukshetra', stateId: 8 },
    { id: 195, name: 'Mahendragarh', stateId: 8 },
    { id: 196, name: 'Nuh', stateId: 8 },
    { id: 197, name: 'Palwal', stateId: 8 },
    { id: 198, name: 'Panchkula', stateId: 8 },
    { id: 199, name: 'Panipat', stateId: 8 },
    { id: 200, name: 'Rewari', stateId: 8 },
    { id: 201, name: 'Rohtak', stateId: 8 },
    { id: 202, name: 'Sirsa', stateId: 8 },
    { id: 203, name: 'Sonipat', stateId: 8 },
    { id: 204, name: 'Yamunanagar', stateId: 8 },

    // Himachal Pradesh (9)
    { id: 205, name: 'Bilaspur', stateId: 9 },
    { id: 206, name: 'Chamba', stateId: 9 },
    { id: 207, name: 'Hamirpur', stateId: 9 },
    { id: 208, name: 'Kangra', stateId: 9 },
    { id: 209, name: 'Kinnaur', stateId: 9 },
    { id: 210, name: 'Kullu', stateId: 9 },
    { id: 211, name: 'Lahaul and Spiti', stateId: 9 },
    { id: 212, name: 'Mandi', stateId: 9 },
    { id: 213, name: 'Shimla', stateId: 9 },
    { id: 214, name: 'Sirmaur', stateId: 9 },
    { id: 215, name: 'Solan', stateId: 9 },
    { id: 216, name: 'Una', stateId: 9 },

    // Jharkhand (10)
    { id: 217, name: 'Bokaro', stateId: 10 },
    { id: 218, name: 'Chatra', stateId: 10 },
    { id: 219, name: 'Deoghar', stateId: 10 },
    { id: 220, name: 'Dhanbad', stateId: 10 },
    { id: 221, name: 'Dumka', stateId: 10 },
    { id: 222, name: 'East Singhbhum', stateId: 10 },
    { id: 223, name: 'Garhwa', stateId: 10 },
    { id: 224, name: 'Giridih', stateId: 10 },
    { id: 225, name: 'Godda', stateId: 10 },
    { id: 226, name: 'Gumla', stateId: 10 },
    { id: 227, name: 'Hazaribagh', stateId: 10 },
    { id: 228, name: 'Jamtara', stateId: 10 },
    { id: 229, name: 'Khunti', stateId: 10 },
    { id: 230, name: 'Koderma', stateId: 10 },
    { id: 231, name: 'Latehar', stateId: 10 },
    { id: 232, name: 'Lohardaga', stateId: 10 },
    { id: 233, name: 'Pakur', stateId: 10 },
    { id: 234, name: 'Palamu', stateId: 10 },
    { id: 235, name: 'Ramgarh', stateId: 10 },
    { id: 236, name: 'Ranchi', stateId: 10 },
    { id: 237, name: 'Sahebganj', stateId: 10 },
    { id: 238, name: 'Saraikela Kharsawan', stateId: 10 },
    { id: 239, name: 'Simdega', stateId: 10 },
    { id: 240, name: 'West Singhbhum', stateId: 10 },

    // Karnataka (11)
    { id: 241, name: 'Bagalkot', stateId: 11 },
    { id: 242, name: 'Bangalore Rural', stateId: 11 },
    { id: 243, name: 'Bangalore Urban', stateId: 11 },
    { id: 244, name: 'Belagavi', stateId: 11 },
    { id: 245, name: 'Bellary', stateId: 11 },
    { id: 246, name: 'Bidar', stateId: 11 },
    { id: 247, name: 'Chamarajanagar', stateId: 11 },
    { id: 248, name: 'Chikballapur', stateId: 11 },
    { id: 249, name: 'Chikkamagaluru', stateId: 11 },
    { id: 250, name: 'Chitradurga', stateId: 11 },
    { id: 251, name: 'Dakshina Kannada', stateId: 11 },
    { id: 252, name: 'Davanagere', stateId: 11 },
    { id: 253, name: 'Dharwad', stateId: 11 },
    { id: 254, name: 'Gadag', stateId: 11 },
    { id: 255, name: 'Hassan', stateId: 11 },
    { id: 256, name: 'Haveri', stateId: 11 },
    { id: 257, name: 'Kalaburagi', stateId: 11 },
    { id: 258, name: 'Kodagu', stateId: 11 },
    { id: 259, name: 'Kolar', stateId: 11 },
    { id: 260, name: 'Koppal', stateId: 11 },
    { id: 261, name: 'Mandya', stateId: 11 },
    { id: 262, name: 'Mysuru', stateId: 11 },
    { id: 263, name: 'Raichur', stateId: 11 },
    { id: 264, name: 'Ramanagara', stateId: 11 },
    { id: 265, name: 'Shivamogga', stateId: 11 },
    { id: 266, name: 'Tumakuru', stateId: 11 },
    { id: 267, name: 'Udupi', stateId: 11 },
    { id: 268, name: 'Uttara Kannada', stateId: 11 },
    { id: 269, name: 'Vijayapura', stateId: 11 },
    { id: 270, name: 'Yadgir', stateId: 11 },

    // Kerala (12)
    { id: 271, name: 'Alappuzha', stateId: 12 },
    { id: 272, name: 'Ernakulam', stateId: 12 },
    { id: 273, name: 'Idukki', stateId: 12 },
    { id: 274, name: 'Kannur', stateId: 12 },
    { id: 275, name: 'Kasaragod', stateId: 12 },
    { id: 276, name: 'Kollam', stateId: 12 },
    { id: 277, name: 'Kottayam', stateId: 12 },
    { id: 278, name: 'Kozhikode', stateId: 12 },
    { id: 279, name: 'Malappuram', stateId: 12 },
    { id: 280, name: 'Palakkad', stateId: 12 },
    { id: 281, name: 'Pathanamthitta', stateId: 12 },
    { id: 282, name: 'Thiruvananthapuram', stateId: 12 },
    { id: 283, name: 'Thrissur', stateId: 12 },
    { id: 284, name: 'Wayanad', stateId: 12 },

    // Madhya Pradesh (13)
    { id: 285, name: 'Agar Malwa', stateId: 13 },
    { id: 286, name: 'Alirajpur', stateId: 13 },
    { id: 287, name: 'Anuppur', stateId: 13 },
    { id: 288, name: 'Ashoknagar', stateId: 13 },
    { id: 289, name: 'Balaghat', stateId: 13 },
    { id: 290, name: 'Barwani', stateId: 13 },
    { id: 291, name: 'Betul', stateId: 13 },
    { id: 292, name: 'Bhind', stateId: 13 },
    { id: 293, name: 'Bhopal', stateId: 13 },
    { id: 294, name: 'Burhanpur', stateId: 13 },
    { id: 295, name: 'Chachaura', stateId: 13 },
    { id: 296, name: 'Chhatarpur', stateId: 13 },
    { id: 297, name: 'Chhindwara', stateId: 13 },
    { id: 298, name: 'Damoh', stateId: 13 },
    { id: 299, name: 'Datia', stateId: 13 },
    { id: 300, name: 'Dewas', stateId: 13 },
    { id: 301, name: 'Dhar', stateId: 13 },
    { id: 302, name: 'Dindori', stateId: 13 },
    { id: 303, name: 'Guna', stateId: 13 },
    { id: 304, name: 'Gwalior', stateId: 13 },
    { id: 305, name: 'Harda', stateId: 13 },
    { id: 306, name: 'Hoshangabad', stateId: 13 },
    { id: 307, name: 'Indore', stateId: 13 },
    { id: 308, name: 'Jabalpur', stateId: 13 },
    { id: 309, name: 'Jhabua', stateId: 13 },
    { id: 310, name: 'Katni', stateId: 13 },
    { id: 311, name: 'Khandwa', stateId: 13 },
    { id: 312, name: 'Khargone', stateId: 13 },
    { id: 313, name: 'Maihar', stateId: 13 },
    { id: 314, name: 'Mandla', stateId: 13 },
    { id: 315, name: 'Mandsaur', stateId: 13 },
    { id: 316, name: 'Morena', stateId: 13 },
    { id: 317, name: 'Narmadapuram', stateId: 13 },
    { id: 318, name: 'Narsinghpur', stateId: 13 },
    { id: 319, name: 'Neemuch', stateId: 13 },
    { id: 320, name: 'Niwari', stateId: 13 },
    { id: 321, name: 'Panna', stateId: 13 },
    { id: 322, name: 'Raisen', stateId: 13 },
    { id: 323, name: 'Rajgarh', stateId: 13 },
    { id: 324, name: 'Ratlam', stateId: 13 },
    { id: 325, name: 'Rewa', stateId: 13 },
    { id: 326, name: 'Sagar', stateId: 13 },
    { id: 327, name: 'Satna', stateId: 13 },
    { id: 328, name: 'Sehore', stateId: 13 },
    { id: 329, name: 'Seoni', stateId: 13 },
    { id: 330, name: 'Shahdol', stateId: 13 },
    { id: 331, name: 'Shajapur', stateId: 13 },
    { id: 332, name: 'Sheopur', stateId: 13 },
    { id: 333, name: 'Shivpuri', stateId: 13 },
    { id: 334, name: 'Sidhi', stateId: 13 },
    { id: 335, name: 'Singrauli', stateId: 13 },
    { id: 336, name: 'Tikamgarh', stateId: 13 },
    { id: 337, name: 'Ujjain', stateId: 13 },
    { id: 338, name: 'Umaria', stateId: 13 },
    { id: 339, name: 'Vidisha', stateId: 13 },

    // Maharashtra (14)
    { id: 340, name: 'Ahmednagar', stateId: 14 },
    { id: 341, name: 'Akola', stateId: 14 },
    { id: 342, name: 'Amravati', stateId: 14 },
    { id: 343, name: 'Beed', stateId: 14 },
    { id: 344, name: 'Bhandara', stateId: 14 },
    { id: 345, name: 'Buldhana', stateId: 14 },
    { id: 346, name: 'Chandrapur', stateId: 14 },
    { id: 347, name: 'Dhule', stateId: 14 },
    { id: 348, name: 'Gadchiroli', stateId: 14 },
    { id: 349, name: 'Gondia', stateId: 14 },
    { id: 350, name: 'Hingoli', stateId: 14 },
    { id: 351, name: 'Jalgaon', stateId: 14 },
    { id: 352, name: 'Jalna', stateId: 14 },
    { id: 353, name: 'Kolhapur', stateId: 14 },
    { id: 354, name: 'Latur', stateId: 14 },
    { id: 355, name: 'Mumbai City', stateId: 14 },
    { id: 356, name: 'Mumbai Suburban', stateId: 14 },
    { id: 357, name: 'Nagpur', stateId: 14 },
    { id: 358, name: 'Nanded', stateId: 14 },
    { id: 359, name: 'Nandurbar', stateId: 14 },
    { id: 360, name: 'Nashik', stateId: 14 },
    { id: 361, name: 'Osmanabad', stateId: 14 },
    { id: 362, name: 'Palghar', stateId: 14 },
    { id: 363, name: 'Parbhani', stateId: 14 },
    { id: 364, name: 'Pune', stateId: 14 },
    { id: 365, name: 'Raigad', stateId: 14 },
    { id: 366, name: 'Ratnagiri', stateId: 14 },
    { id: 367, name: 'Sangli', stateId: 14 },
    { id: 368, name: 'Satara', stateId: 14 },
    { id: 369, name: 'Sindhudurg', stateId: 14 },
    { id: 370, name: 'Solapur', stateId: 14 },
    { id: 371, name: 'Thane', stateId: 14 },
    { id: 372, name: 'Wardha', stateId: 14 },
    { id: 373, name: 'Washim', stateId: 14 },
    { id: 374, name: 'Yavatmal', stateId: 14 },

    // Manipur (15)
    { id: 375, name: 'Bishnupur', stateId: 15 },
    { id: 376, name: 'Chandel', stateId: 15 },
    { id: 377, name: 'Churachandpur', stateId: 15 },
    { id: 378, name: 'Imphal East', stateId: 15 },
    { id: 379, name: 'Imphal West', stateId: 15 },
    { id: 380, name: 'Jiribam', stateId: 15 },
    { id: 381, name: 'Kakching', stateId: 15 },
    { id: 382, name: 'Kamjong', stateId: 15 },
    { id: 383, name: 'Kangpokpi', stateId: 15 },
    { id: 384, name: 'Noney', stateId: 15 },
    { id: 385, name: 'Pherzawl', stateId: 15 },
    { id: 386, name: 'Senapati', stateId: 15 },
    { id: 387, name: 'Tamenglong', stateId: 15 },
    { id: 388, name: 'Tengnoupal', stateId: 15 },
    { id: 389, name: 'Thoubal', stateId: 15 },
    { id: 390, name: 'Ukhrul', stateId: 15 },

    // Meghalaya (16)
    { id: 391, name: 'East Garo Hills', stateId: 16 },
    { id: 392, name: 'East Jaintia Hills', stateId: 16 },
    { id: 393, name: 'East Khasi Hills', stateId: 16 },
    { id: 394, name: 'North Garo Hills', stateId: 16 },
    { id: 395, name: 'Ri Bhoi', stateId: 16 },
    { id: 396, name: 'South Garo Hills', stateId: 16 },
    { id: 397, name: 'South West Garo Hills', stateId: 16 },
    { id: 398, name: 'South West Khasi Hills', stateId: 16 },
    { id: 399, name: 'West Garo Hills', stateId: 16 },
    { id: 400, name: 'West Jaintia Hills', stateId: 16 },
    { id: 401, name: 'West Khasi Hills', stateId: 16 },

    // Mizoram (17)
    { id: 402, name: 'Aizawl', stateId: 17 },
    { id: 403, name: 'Champhai', stateId: 17 },
    { id: 404, name: 'Hnahthial', stateId: 17 },
    { id: 405, name: 'Khawzawl', stateId: 17 },
    { id: 406, name: 'Kolasib', stateId: 17 },
    { id: 407, name: 'Lawngtlai', stateId: 17 },
    { id: 408, name: 'Lunglei', stateId: 17 },
    { id: 409, name: 'Mamit', stateId: 17 },
    { id: 410, name: 'Saiha', stateId: 17 },
    { id: 411, name: 'Saitual', stateId: 17 },
    { id: 412, name: 'Serchhip', stateId: 17 },

    // Nagaland (18)
    { id: 413, name: 'Chumoukedima', stateId: 18 },
    { id: 414, name: 'Dimapur', stateId: 18 },
    { id: 415, name: 'Kiphire', stateId: 18 },
    { id: 416, name: 'Kohima', stateId: 18 },
    { id: 417, name: 'Longleng', stateId: 18 },
    { id: 418, name: 'Mokokchung', stateId: 18 },
    { id: 419, name: 'Mon', stateId: 18 },
    { id: 420, name: 'Niuland', stateId: 18 },
    { id: 421, name: 'Noklak', stateId: 18 },
    { id: 422, name: 'Peren', stateId: 18 },
    { id: 423, name: 'Phek', stateId: 18 },
    { id: 424, name: 'Shamator', stateId: 18 },
    { id: 425, name: 'Tseminyu', stateId: 18 },
    { id: 426, name: 'Tuensang', stateId: 18 },
    { id: 427, name: 'Wokha', stateId: 18 },
    { id: 428, name: 'Zunheboto', stateId: 18 },

    // Odisha (19)
    { id: 429, name: 'Angul', stateId: 19 },
    { id: 430, name: 'Balangir', stateId: 19 },
    { id: 431, name: 'Balasore', stateId: 19 },
    { id: 432, name: 'Bargarh', stateId: 19 },
    { id: 433, name: 'Bhadrak', stateId: 19 },
    { id: 434, name: 'Boudh', stateId: 19 },
    { id: 435, name: 'Cuttack', stateId: 19 },
    { id: 436, name: 'Debagarh', stateId: 19 },
    { id: 437, name: 'Dhenkanal', stateId: 19 },
    { id: 438, name: 'Gajapati', stateId: 19 },
    { id: 439, name: 'Ganjam', stateId: 19 },
    { id: 440, name: 'Jagatsinghpur', stateId: 19 },
    { id: 441, name: 'Jajpur', stateId: 19 },
    { id: 442, name: 'Jharsuguda', stateId: 19 },
    { id: 443, name: 'Kalahandi', stateId: 19 },
    { id: 444, name: 'Kandhamal', stateId: 19 },
    { id: 445, name: 'Kendrapara', stateId: 19 },
    { id: 446, name: 'Kendujhar', stateId: 19 },
    { id: 447, name: 'Khordha', stateId: 19 },
    { id: 448, name: 'Koraput', stateId: 19 },
    { id: 449, name: 'Malkangiri', stateId: 19 },
    { id: 450, name: 'Mayurbhanj', stateId: 19 },
    { id: 451, name: 'Nabarangpur', stateId: 19 },
    { id: 452, name: 'Nayagarh', stateId: 19 },
    { id: 453, name: 'Nuapada', stateId: 19 },
    { id: 454, name: 'Puri', stateId: 19 },
    { id: 455, name: 'Rayagada', stateId: 19 },
    { id: 456, name: 'Sambalpur', stateId: 19 },
    { id: 457, name: 'Subarnapur', stateId: 19 },
    { id: 458, name: 'Sundergarh', stateId: 19 },

    // Punjab (20)
    { id: 459, name: 'Amritsar', stateId: 20 },
    { id: 460, name: 'Barnala', stateId: 20 },
    { id: 461, name: 'Bathinda', stateId: 20 },
    { id: 462, name: 'Faridkot', stateId: 20 },
    { id: 463, name: 'Fatehgarh Sahib', stateId: 20 },
    { id: 464, name: 'Fazilka', stateId: 20 },
    { id: 465, name: 'Firozpur', stateId: 20 },
    { id: 466, name: 'Gurdaspur', stateId: 20 },
    { id: 467, name: 'Hoshiarpur', stateId: 20 },
    { id: 468, name: 'Jalandhar', stateId: 20 },
    { id: 469, name: 'Kapurthala', stateId: 20 },
    { id: 470, name: 'Ludhiana', stateId: 20 },
    { id: 471, name: 'Malerkotla', stateId: 20 },
    { id: 472, name: 'Mansa', stateId: 20 },
    { id: 473, name: 'Moga', stateId: 20 },
    { id: 474, name: 'Pathankot', stateId: 20 },
    { id: 475, name: 'Patiala', stateId: 20 },
    { id: 476, name: 'Rupnagar', stateId: 20 },
    { id: 477, name: 'Sangrur', stateId: 20 },
    { id: 478, name: 'Shaheed Bhagat Singh Nagar', stateId: 20 },
    { id: 479, name: 'Sri Muktsar Sahib', stateId: 20 },
    { id: 480, name: 'Tarn Taran', stateId: 20 },

    // Rajasthan (21)
    { id: 481, name: 'Ajmer', stateId: 21 },
    { id: 482, name: 'Alwar', stateId: 21 },
    { id: 483, name: 'Banswara', stateId: 21 },
    { id: 484, name: 'Baran', stateId: 21 },
    { id: 485, name: 'Barmer', stateId: 21 },
    { id: 486, name: 'Bharatpur', stateId: 21 },
    { id: 487, name: 'Bhilwara', stateId: 21 },
    { id: 488, name: 'Bikaner', stateId: 21 },
    { id: 489, name: 'Bundi', stateId: 21 },
    { id: 490, name: 'Chittorgarh', stateId: 21 },
    { id: 491, name: 'Churu', stateId: 21 },
    { id: 492, name: 'Dausa', stateId: 21 },
    { id: 493, name: 'Dholpur', stateId: 21 },
    { id: 494, name: 'Dungarpur', stateId: 21 },
    { id: 495, name: 'Hanumangarh', stateId: 21 },
    { id: 496, name: 'Jaipur', stateId: 21 },
    { id: 497, name: 'Jaisalmer', stateId: 21 },
    { id: 498, name: 'Jalore', stateId: 21 },
    { id: 499, name: 'Jhalawar', stateId: 21 },
    { id: 500, name: 'Jhunjhunu', stateId: 21 },
    { id: 501, name: 'Jodhpur', stateId: 21 },
    { id: 502, name: 'Karauli', stateId: 21 },
    { id: 503, name: 'Kota', stateId: 21 },
    { id: 504, name: 'Nagaur', stateId: 21 },
    { id: 505, name: 'Pali', stateId: 21 },
    { id: 506, name: 'Pratapgarh', stateId: 21 },
    { id: 507, name: 'Rajsamand', stateId: 21 },
    { id: 508, name: 'Sawai Madhopur', stateId: 21 },
    { id: 509, name: 'Sikar', stateId: 21 },
    { id: 510, name: 'Sirohi', stateId: 21 },
    { id: 511, name: 'Sri Ganganagar', stateId: 21 },
    { id: 512, name: 'Tonk', stateId: 21 },
    { id: 513, name: 'Udaipur', stateId: 21 },

    // Sikkim (22)
    { id: 514, name: 'Gangtok', stateId: 22 },
    { id: 515, name: 'Mangan', stateId: 22 },
    { id: 516, name: 'Namchi', stateId: 22 },
    { id: 517, name: 'Pakyong', stateId: 22 },
    { id: 518, name: 'Soreng', stateId: 22 },

    // Tamil Nadu (23)
    { id: 519, name: 'Ariyalur', stateId: 23 },
    { id: 520, name: 'Chengalpattu', stateId: 23 },
    { id: 521, name: 'Chennai', stateId: 23 },
    { id: 522, name: 'Coimbatore', stateId: 23 },
    { id: 523, name: 'Cuddalore', stateId: 23 },
    { id: 524, name: 'Dharmapuri', stateId: 23 },
    { id: 525, name: 'Dindigul', stateId: 23 },
    { id: 526, name: 'Erode', stateId: 23 },
    { id: 527, name: 'Kallakurichi', stateId: 23 },
    { id: 528, name: 'Kanchipuram', stateId: 23 },
    { id: 529, name: 'Kanyakumari', stateId: 23 },
    { id: 530, name: 'Karur', stateId: 23 },
    { id: 531, name: 'Krishnagiri', stateId: 23 },
    { id: 532, name: 'Madurai', stateId: 23 },
    { id: 533, name: 'Mayiladuthurai', stateId: 23 },
    { id: 534, name: 'Nagapattinam', stateId: 23 },
    { id: 535, name: 'Namakkal', stateId: 23 },
    { id: 536, name: 'Nilgiris', stateId: 23 },
    { id: 537, name: 'Perambalur', stateId: 23 },
    { id: 538, name: 'Pudukkottai', stateId: 23 },
    { id: 539, name: 'Ramanathapuram', stateId: 23 },
    { id: 540, name: 'Ranipet', stateId: 23 },
    { id: 541, name: 'Salem', stateId: 23 },
    { id: 542, name: 'Sivaganga', stateId: 23 },
    { id: 543, name: 'Tenkasi', stateId: 23 },
    { id: 544, name: 'Thanjavur', stateId: 23 },
    { id: 545, name: 'Theni', stateId: 23 },
    { id: 546, name: 'Thoothukudi', stateId: 23 },
    { id: 547, name: 'Tiruchirappalli', stateId: 23 },
    { id: 548, name: 'Tirunelveli', stateId: 23 },
    { id: 549, name: 'Tirupathur', stateId: 23 },
    { id: 550, name: 'Tiruppur', stateId: 23 },
    { id: 551, name: 'Tiruvallur', stateId: 23 },
    { id: 552, name: 'Tiruvannamalai', stateId: 23 },
    { id: 553, name: 'Vellore', stateId: 23 },
    { id: 554, name: 'Viluppuram', stateId: 23 },
    { id: 555, name: 'Virudhunagar', stateId: 23 },

    // Telangana (24)
    { id: 556, name: 'Adilabad', stateId: 24 },
    { id: 557, name: 'Bhadradri Kothagudem', stateId: 24 },
    { id: 558, name: 'Hanamkonda', stateId: 24 },
    { id: 559, name: 'Hyderabad', stateId: 24 },
    { id: 560, name: 'Jagtial', stateId: 24 },
    { id: 561, name: 'Jangaon', stateId: 24 },
    { id: 562, name: 'Jayashankar Bhupalpally', stateId: 24 },
    { id: 563, name: 'Jogulamba Gadwal', stateId: 24 },
    { id: 564, name: 'Kamareddy', stateId: 24 },
    { id: 565, name: 'Karimnagar', stateId: 24 },
    { id: 566, name: 'Khammam', stateId: 24 },
    { id: 567, name: 'Kumuram Bheem', stateId: 24 },
    { id: 568, name: 'Mahabubabad', stateId: 24 },
    { id: 569, name: 'Mahabubnagar', stateId: 24 },
    { id: 570, name: 'Mancherial', stateId: 24 },
    { id: 571, name: 'Medak', stateId: 24 },
    { id: 572, name: 'Medchal-Malkajgiri', stateId: 24 },
    { id: 573, name: 'Mulugu', stateId: 24 },
    { id: 574, name: 'Nagarkurnool', stateId: 24 },
    { id: 575, name: 'Nalgonda', stateId: 24 },
    { id: 576, name: 'Narayanpet', stateId: 24 },
    { id: 577, name: 'Nirmal', stateId: 24 },
    { id: 578, name: 'Nizamabad', stateId: 24 },
    { id: 579, name: 'Peddapalli', stateId: 24 },
    { id: 580, name: 'Rajanna Sircilla', stateId: 24 },
    { id: 581, name: 'Ranga Reddy', stateId: 24 },
    { id: 582, name: 'Sangareddy', stateId: 24 },
    { id: 583, name: 'Siddipet', stateId: 24 },
    { id: 584, name: 'Suryapet', stateId: 24 },
    { id: 585, name: 'Vikarabad', stateId: 24 },
    { id: 586, name: 'Wanaparthy', stateId: 24 },
    { id: 587, name: 'Warangal', stateId: 24 },
    { id: 588, name: 'Yadadri Bhuvanagiri', stateId: 24 },

    // Tripura (25)
    { id: 589, name: 'Dhalai', stateId: 25 },
    { id: 590, name: 'Gomati', stateId: 25 },
    { id: 591, name: 'Khowai', stateId: 25 },
    { id: 592, name: 'North Tripura', stateId: 25 },
    { id: 593, name: 'Sepahijala', stateId: 25 },
    { id: 594, name: 'South Tripura', stateId: 25 },
    { id: 595, name: 'Unakoti', stateId: 25 },
    { id: 596, name: 'West Tripura', stateId: 25 },

    // Uttar Pradesh (26)
    { id: 597, name: 'Agra', stateId: 26 },
    { id: 598, name: 'Aligarh', stateId: 26 },
    { id: 599, name: 'Ambedkar Nagar', stateId: 26 },
    { id: 600, name: 'Amethi', stateId: 26 },
    { id: 601, name: 'Amroha', stateId: 26 },
    { id: 602, name: 'Auraiya', stateId: 26 },
    { id: 603, name: 'Ayodhya', stateId: 26 },
    { id: 604, name: 'Azamgarh', stateId: 26 },
    { id: 605, name: 'Badaun', stateId: 26 },
    { id: 606, name: 'Baghpat', stateId: 26 },
    { id: 607, name: 'Bahraich', stateId: 26 },
    { id: 608, name: 'Ballia', stateId: 26 },
    { id: 609, name: 'Balrampur', stateId: 26 },
    { id: 610, name: 'Banda', stateId: 26 },
    { id: 611, name: 'Barabanki', stateId: 26 },
    { id: 612, name: 'Bareilly', stateId: 26 },
    { id: 613, name: 'Basti', stateId: 26 },
    { id: 614, name: 'Bhadohi', stateId: 26 },
    { id: 615, name: 'Bijnor', stateId: 26 },
    { id: 616, name: 'Bulandshahr', stateId: 26 },
    { id: 617, name: 'Chandauli', stateId: 26 },
    { id: 618, name: 'Chitrakoot', stateId: 26 },
    { id: 619, name: 'Deoria', stateId: 26 },
    { id: 620, name: 'Etah', stateId: 26 },
    { id: 621, name: 'Etawah', stateId: 26 },
    { id: 622, name: 'Farrukhabad', stateId: 26 },
    { id: 623, name: 'Fatehpur', stateId: 26 },
    { id: 624, name: 'Firozabad', stateId: 26 },
    { id: 625, name: 'Gautam Buddha Nagar', stateId: 26 },
    { id: 626, name: 'Ghaziabad', stateId: 26 },
    { id: 627, name: 'Ghazipur', stateId: 26 },
    { id: 628, name: 'Gonda', stateId: 26 },
    { id: 629, name: 'Gorakhpur', stateId: 26 },
    { id: 630, name: 'Hamirpur', stateId: 26 },
    { id: 631, name: 'Hapur', stateId: 26 },
    { id: 632, name: 'Hardoi', stateId: 26 },
    { id: 633, name: 'Hathras', stateId: 26 },
    { id: 634, name: 'Jalaun', stateId: 26 },
    { id: 635, name: 'Jaunpur', stateId: 26 },
    { id: 636, name: 'Jhansi', stateId: 26 },
    { id: 637, name: 'Kannauj', stateId: 26 },
    { id: 638, name: 'Kanpur Dehat', stateId: 26 },
    { id: 639, name: 'Kanpur Nagar', stateId: 26 },
    { id: 640, name: 'Kasganj', stateId: 26 },
    { id: 641, name: 'Kaushambi', stateId: 26 },
    { id: 642, name: 'Kheri', stateId: 26 },
    { id: 643, name: 'Kushinagar', stateId: 26 },
    { id: 644, name: 'Lalitpur', stateId: 26 },
    { id: 645, name: 'Lucknow', stateId: 26 },
    { id: 646, name: 'Maharajganj', stateId: 26 },
    { id: 647, name: 'Mahoba', stateId: 26 },
    { id: 648, name: 'Mainpuri', stateId: 26 },
    { id: 649, name: 'Mathura', stateId: 26 },
    { id: 650, name: 'Mau', stateId: 26 },
    { id: 651, name: 'Meerut', stateId: 26 },
    { id: 652, name: 'Mirzapur', stateId: 26 },
    { id: 653, name: 'Moradabad', stateId: 26 },
    { id: 654, name: 'Muzaffarnagar', stateId: 26 },
    { id: 655, name: 'Pilibhit', stateId: 26 },
    { id: 656, name: 'Pratapgarh', stateId: 26 },
    { id: 657, name: 'Prayagraj', stateId: 26 },
    { id: 658, name: 'Raebareli', stateId: 26 },
    { id: 659, name: 'Rampur', stateId: 26 },
    { id: 660, name: 'Saharanpur', stateId: 26 },
    { id: 661, name: 'Sambhal', stateId: 26 },
    { id: 662, name: 'Sant Kabir Nagar', stateId: 26 },
    { id: 663, name: 'Shahjahanpur', stateId: 26 },
    { id: 664, name: 'Shamli', stateId: 26 },
    { id: 665, name: 'Shravasti', stateId: 26 },
    { id: 666, name: 'Siddharthnagar', stateId: 26 },
    { id: 667, name: 'Sitapur', stateId: 26 },
    { id: 668, name: 'Sonbhadra', stateId: 26 },
    { id: 669, name: 'Sultanpur', stateId: 26 },
    { id: 670, name: 'Unnao', stateId: 26 },
    { id: 671, name: 'Varanasi', stateId: 26 },

    // Uttarakhand (27)
    { id: 672, name: 'Almora', stateId: 27 },
    { id: 673, name: 'Bageshwar', stateId: 27 },
    { id: 674, name: 'Chamoli', stateId: 27 },
    { id: 675, name: 'Champawat', stateId: 27 },
    { id: 676, name: 'Dehradun', stateId: 27 },
    { id: 677, name: 'Haridwar', stateId: 27 },
    { id: 678, name: 'Nainital', stateId: 27 },
    { id: 679, name: 'Pauri Garhwal', stateId: 27 },
    { id: 680, name: 'Pithoragarh', stateId: 27 },
    { id: 681, name: 'Rudraprayag', stateId: 27 },
    { id: 682, name: 'Tehri Garhwal', stateId: 27 },
    { id: 683, name: 'Udham Singh Nagar', stateId: 27 },
    { id: 684, name: 'Uttarkashi', stateId: 27 },

    // West Bengal (28)
    { id: 685, name: 'Alipurduar', stateId: 28 },
    { id: 686, name: 'Bankura', stateId: 28 },
    { id: 687, name: 'Birbhum', stateId: 28 },
    { id: 688, name: 'Cooch Behar', stateId: 28 },
    { id: 689, name: 'Dakshin Dinajpur', stateId: 28 },
    { id: 690, name: 'Darjeeling', stateId: 28 },
    { id: 691, name: 'Hooghly', stateId: 28 },
    { id: 692, name: 'Howrah', stateId: 28 },
    { id: 693, name: 'Jalpaiguri', stateId: 28 },
    { id: 694, name: 'Jhargram', stateId: 28 },
    { id: 695, name: 'Kalimpong', stateId: 28 },
    { id: 696, name: 'Kolkata', stateId: 28 },
    { id: 697, name: 'Malda', stateId: 28 },
    { id: 698, name: 'Murshidabad', stateId: 28 },
    { id: 699, name: 'Nadia', stateId: 28 },
    { id: 700, name: 'North 24 Parganas', stateId: 28 },
    { id: 701, name: 'Paschim Bardhaman', stateId: 28 },
    { id: 702, name: 'Paschim Medinipur', stateId: 28 },
    { id: 703, name: 'Purba Bardhaman', stateId: 28 },
    { id: 704, name: 'Purba Medinipur', stateId: 28 },
    { id: 705, name: 'Purulia', stateId: 28 },
    { id: 706, name: 'South 24 Parganas', stateId: 28 },
    { id: 707, name: 'Uttar Dinajpur', stateId: 28 },

    // Andaman and Nicobar Islands (29)
    { id: 708, name: 'Nicobar', stateId: 29 },
    { id: 709, name: 'North and Middle Andaman', stateId: 29 },
    { id: 710, name: 'South Andaman', stateId: 29 },

    // Chandigarh (30)
    { id: 711, name: 'Chandigarh', stateId: 30 },

    // Dadra and Nagar Haveli and Daman and Diu (31)
    { id: 712, name: 'Dadra and Nagar Haveli', stateId: 31 },
    { id: 713, name: 'Daman', stateId: 31 },
    { id: 714, name: 'Diu', stateId: 31 },

    // Delhi (32)
    { id: 715, name: 'Central Delhi', stateId: 32 },
    { id: 716, name: 'East Delhi', stateId: 32 },
    { id: 717, name: 'New Delhi', stateId: 32 },
    { id: 718, name: 'North Delhi', stateId: 32 },
    { id: 719, name: 'North East Delhi', stateId: 32 },
    { id: 720, name: 'North West Delhi', stateId: 32 },
    { id: 721, name: 'Shahdara', stateId: 32 },
    { id: 722, name: 'South Delhi', stateId: 32 },
    { id: 723, name: 'South East Delhi', stateId: 32 },
    { id: 724, name: 'South West Delhi', stateId: 32 },
    { id: 725, name: 'West Delhi', stateId: 32 },

    // Jammu and Kashmir (33)
    { id: 726, name: 'Anantnag', stateId: 33 },
    { id: 727, name: 'Bandipora', stateId: 33 },
    { id: 728, name: 'Baramulla', stateId: 33 },
    { id: 729, name: 'Budgam', stateId: 33 },
    { id: 730, name: 'Doda', stateId: 33 },
    { id: 731, name: 'Ganderbal', stateId: 33 },
    { id: 732, name: 'Jammu', stateId: 33 },
    { id: 733, name: 'Kathua', stateId: 33 },
    { id: 734, name: 'Kishtwar', stateId: 33 },
    { id: 735, name: 'Kulgam', stateId: 33 },
    { id: 736, name: 'Kupwara', stateId: 33 },
    { id: 737, name: 'Poonch', stateId: 33 },
    { id: 738, name: 'Pulwama', stateId: 33 },
    { id: 739, name: 'Rajouri', stateId: 33 },
    { id: 740, name: 'Ramban', stateId: 33 },
    { id: 741, name: 'Reasi', stateId: 33 },
    { id: 742, name: 'Samba', stateId: 33 },
    { id: 743, name: 'Shopian', stateId: 33 },
    { id: 744, name: 'Srinagar', stateId: 33 },
    { id: 745, name: 'Udhampur', stateId: 33 },

    // Ladakh (34)
    { id: 746, name: 'Kargil', stateId: 34 },
    { id: 747, name: 'Leh', stateId: 34 },

    // Lakshadweep (35)
    { id: 748, name: 'Lakshadweep', stateId: 35 },

    // Puducherry (36)
    { id: 749, name: 'Karaikal', stateId: 36 },
    { id: 750, name: 'Mahe', stateId: 36 },
    { id: 751, name: 'Puducherry', stateId: 36 },
    { id: 752, name: 'Yanam', stateId: 36 },
  ]

  for (const d of districtsData) {
    await prisma.district.upsert({
      where: { id: d.id },
      update: { name: d.name, stateId: d.stateId },
      create: d,
    })
  }
  console.log(`Seeded ${districtsData.length} districts`)

  // ----- CITIES -----
  // Major Indian cities mapped to their district IDs
  // Format: { id, name, districtId }
  const citiesData: { id: number; name: string; districtId: number }[] = [
    // Andhra Pradesh
    { id: 1, name: 'Visakhapatnam', districtId: 19 },
    { id: 2, name: 'Vijayawada', districtId: 11 },
    { id: 3, name: 'Guntur', districtId: 8 },
    { id: 4, name: 'Nellore', districtId: 14 },
    { id: 5, name: 'Kurnool', districtId: 12 },
    { id: 6, name: 'Tirupati', districtId: 5 },
    { id: 7, name: 'Rajahmundry', districtId: 6 },
    { id: 8, name: 'Kakinada', districtId: 9 },
    { id: 9, name: 'Anantapur', districtId: 2 },
    { id: 10, name: 'Eluru', districtId: 7 },
    { id: 11, name: 'Kadapa', districtId: 22 },
    { id: 12, name: 'Ongole', districtId: 16 },
    { id: 13, name: 'Chittoor', districtId: 5 },
    { id: 14, name: 'Machilipatnam', districtId: 11 },
    { id: 15, name: 'Tenali', districtId: 8 },

    // Arunachal Pradesh
    { id: 16, name: 'Itanagar', districtId: 48 },
    { id: 17, name: 'Tawang', districtId: 42 },
    { id: 18, name: 'Pasighat', districtId: 27 },

    // Assam
    { id: 19, name: 'Guwahati', districtId: 67 },
    { id: 20, name: 'Silchar', districtId: 53 },
    { id: 21, name: 'Dibrugarh', districtId: 59 },
    { id: 22, name: 'Jorhat', districtId: 65 },
    { id: 23, name: 'Nagaon', districtId: 74 },
    { id: 24, name: 'Tinsukia', districtId: 79 },
    { id: 25, name: 'Tezpur', districtId: 77 },
    { id: 26, name: 'Bongaigaon', districtId: 52 },

    // Bihar
    { id: 27, name: 'Patna', districtId: 107 },
    { id: 28, name: 'Gaya', districtId: 92 },
    { id: 29, name: 'Bhagalpur', districtId: 87 },
    { id: 30, name: 'Muzaffarpur', districtId: 104 },
    { id: 31, name: 'Darbhanga', districtId: 90 },
    { id: 32, name: 'Purnia', districtId: 108 },
    { id: 33, name: 'Begusarai', districtId: 86 },
    { id: 34, name: 'Katihar', districtId: 97 },

    // Chhattisgarh
    { id: 35, name: 'Raipur', districtId: 143 },
    { id: 36, name: 'Bhilai', districtId: 143 },
    { id: 37, name: 'Bilaspur', districtId: 126 },
    { id: 38, name: 'Korba', districtId: 137 },
    { id: 39, name: 'Raigarh', districtId: 142 },
    { id: 40, name: 'Durg', districtId: 129 },

    // Goa
    { id: 41, name: 'Panaji', districtId: 148 },
    { id: 42, name: 'Margao', districtId: 149 },
    { id: 43, name: 'Vasco da Gama', districtId: 149 },

    // Gujarat
    { id: 44, name: 'Ahmedabad', districtId: 150 },
    { id: 45, name: 'Surat', districtId: 178 },
    { id: 46, name: 'Vadodara', districtId: 181 },
    { id: 47, name: 'Rajkot', districtId: 176 },
    { id: 48, name: 'Bhavnagar', districtId: 156 },
    { id: 49, name: 'Jamnagar', districtId: 164 },
    { id: 50, name: 'Junagadh', districtId: 165 },
    { id: 51, name: 'Gandhinagar', districtId: 162 },
    { id: 52, name: 'Anand', districtId: 152 },
    { id: 53, name: 'Nadiad', districtId: 166 },
    { id: 54, name: 'Mehsana', districtId: 169 },
    { id: 55, name: 'Bharuch', districtId: 155 },
    { id: 56, name: 'Navsari', districtId: 172 },
    { id: 57, name: 'Morbi', districtId: 170 },

    // Haryana
    { id: 58, name: 'Chandigarh', districtId: 711 },
    { id: 59, name: 'Faridabad', districtId: 186 },
    { id: 60, name: 'Gurugram', districtId: 188 },
    { id: 61, name: 'Panipat', districtId: 199 },
    { id: 62, name: 'Ambala', districtId: 183 },
    { id: 63, name: 'Karnal', districtId: 193 },
    { id: 64, name: 'Sonipat', districtId: 203 },
    { id: 65, name: 'Rohtak', districtId: 201 },
    { id: 66, name: 'Hisar', districtId: 189 },
    { id: 67, name: 'Panchkula', districtId: 198 },

    // Himachal Pradesh
    { id: 68, name: 'Shimla', districtId: 213 },
    { id: 69, name: 'Dharamshala', districtId: 208 },
    { id: 70, name: 'Mandi', districtId: 212 },
    { id: 71, name: 'Solan', districtId: 215 },
    { id: 72, name: 'Kullu', districtId: 210 },
    { id: 73, name: 'Hamirpur', districtId: 207 },

    // Jharkhand
    { id: 74, name: 'Ranchi', districtId: 236 },
    { id: 75, name: 'Jamshedpur', districtId: 222 },
    { id: 76, name: 'Dhanbad', districtId: 220 },
    { id: 77, name: 'Bokaro', districtId: 217 },
    { id: 78, name: 'Deoghar', districtId: 219 },
    { id: 79, name: 'Hazaribagh', districtId: 227 },

    // Karnataka
    { id: 80, name: 'Bengaluru', districtId: 243 },
    { id: 81, name: 'Mysuru', districtId: 262 },
    { id: 82, name: 'Hubballi', districtId: 254 },
    { id: 83, name: 'Mangaluru', districtId: 251 },
    { id: 84, name: 'Belagavi', districtId: 244 },
    { id: 85, name: 'Davangere', districtId: 252 },
    { id: 86, name: 'Bellary', districtId: 245 },
    { id: 87, name: 'Gulbarga', districtId: 257 },
    { id: 88, name: 'Shivamogga', districtId: 265 },
    { id: 89, name: 'Tumakuru', districtId: 266 },
    { id: 90, name: 'Udupi', districtId: 267 },

    // Kerala
    { id: 91, name: 'Thiruvananthapuram', districtId: 282 },
    { id: 92, name: 'Kochi', districtId: 272 },
    { id: 93, name: 'Kozhikode', districtId: 278 },
    { id: 94, name: 'Thrissur', districtId: 283 },
    { id: 95, name: 'Kollam', districtId: 276 },
    { id: 96, name: 'Alappuzha', districtId: 271 },
    { id: 97, name: 'Kannur', districtId: 274 },
    { id: 98, name: 'Palakkad', districtId: 280 },
    { id: 99, name: 'Kottayam', districtId: 277 },
    { id: 100, name: 'Malappuram', districtId: 279 },

    // Madhya Pradesh
    { id: 101, name: 'Indore', districtId: 307 },
    { id: 102, name: 'Bhopal', districtId: 293 },
    { id: 103, name: 'Jabalpur', districtId: 308 },
    { id: 104, name: 'Gwalior', districtId: 304 },
    { id: 105, name: 'Ujjain', districtId: 337 },
    { id: 106, name: 'Sagar', districtId: 326 },
    { id: 107, name: 'Dewas', districtId: 300 },
    { id: 108, name: 'Satna', districtId: 327 },
    { id: 109, name: 'Ratlam', districtId: 324 },
    { id: 110, name: 'Rewa', districtId: 325 },
    { id: 111, name: 'Murwara', districtId: 310 },
    { id: 112, name: 'Singrauli', districtId: 335 },
    { id: 113, name: 'Burhanpur', districtId: 294 },
    { id: 114, name: 'Khandwa', districtId: 311 },
    { id: 115, name: 'Morena', districtId: 316 },

    // Maharashtra
    { id: 116, name: 'Mumbai', districtId: 355 },
    { id: 117, name: 'Pune', districtId: 364 },
    { id: 118, name: 'Nagpur', districtId: 357 },
    { id: 119, name: 'Thane', districtId: 371 },
    { id: 120, name: 'Nashik', districtId: 360 },
    { id: 121, name: 'Aurangabad', districtId: 340 },
    { id: 122, name: 'Solapur', districtId: 370 },
    { id: 123, name: 'Kolhapur', districtId: 353 },
    { id: 124, name: 'Amravati', districtId: 342 },
    { id: 125, name: 'Navi Mumbai', districtId: 371 },
    { id: 126, name: 'Sangli', districtId: 367 },
    { id: 127, name: 'Malegaon', districtId: 360 },
    { id: 128, name: 'Jalgaon', districtId: 351 },
    { id: 129, name: 'Akola', districtId: 341 },
    { id: 130, name: 'Latur', districtId: 354 },
    { id: 131, name: 'Ahmednagar', districtId: 340 },
    { id: 132, name: 'Dhule', districtId: 347 },
    { id: 133, name: 'Chandrapur', districtId: 346 },
    { id: 134, name: 'Parbhani', districtId: 363 },
    { id: 135, name: 'Nanded', districtId: 358 },

    // Manipur
    { id: 136, name: 'Imphal', districtId: 379 },

    // Meghalaya
    { id: 137, name: 'Shillong', districtId: 393 },
    { id: 138, name: 'Tura', districtId: 399 },

    // Mizoram
    { id: 139, name: 'Aizawl', districtId: 402 },
    { id: 140, name: 'Lunglei', districtId: 408 },

    // Nagaland
    { id: 141, name: 'Kohima', districtId: 416 },
    { id: 142, name: 'Dimapur', districtId: 414 },

    // Odisha
    { id: 143, name: 'Bhubaneswar', districtId: 447 },
    { id: 144, name: 'Cuttack', districtId: 435 },
    { id: 145, name: 'Rourkela', districtId: 458 },
    { id: 146, name: 'Berhampur', districtId: 439 },
    { id: 147, name: 'Sambalpur', districtId: 456 },
    { id: 148, name: 'Puri', districtId: 454 },
    { id: 149, name: 'Balasore', districtId: 431 },

    // Punjab
    { id: 150, name: 'Ludhiana', districtId: 470 },
    { id: 151, name: 'Amritsar', districtId: 459 },
    { id: 152, name: 'Jalandhar', districtId: 468 },
    { id: 153, name: 'Patiala', districtId: 475 },
    { id: 154, name: 'Bathinda', districtId: 461 },
    { id: 155, name: 'Mohali', districtId: 476 },
    { id: 156, name: 'Hoshiarpur', districtId: 467 },
    { id: 157, name: 'Batala', districtId: 459 },
    { id: 158, name: 'Pathankot', districtId: 474 },

    // Rajasthan
    { id: 159, name: 'Jaipur', districtId: 496 },
    { id: 160, name: 'Jodhpur', districtId: 501 },
    { id: 161, name: 'Udaipur', districtId: 513 },
    { id: 162, name: 'Kota', districtId: 503 },
    { id: 163, name: 'Bikaner', districtId: 488 },
    { id: 164, name: 'Ajmer', districtId: 481 },
    { id: 165, name: 'Bhilwara', districtId: 487 },
    { id: 166, name: 'Alwar', districtId: 482 },
    { id: 167, name: 'Bharatpur', districtId: 485 },
    { id: 168, name: 'Sikar', districtId: 509 },
    { id: 169, name: 'Pali', districtId: 505 },
    { id: 170, name: 'Sri Ganganagar', districtId: 511 },
    { id: 171, name: 'Tonk', districtId: 512 },
    { id: 172, name: 'Kishangarh', districtId: 481 },

    // Sikkim
    { id: 173, name: 'Gangtok', districtId: 514 },

    // Tamil Nadu
    { id: 174, name: 'Chennai', districtId: 521 },
    { id: 175, name: 'Coimbatore', districtId: 522 },
    { id: 176, name: 'Madurai', districtId: 532 },
    { id: 177, name: 'Tiruchirappalli', districtId: 547 },
    { id: 178, name: 'Salem', districtId: 541 },
    { id: 179, name: 'Tirunelveli', districtId: 548 },
    { id: 180, name: 'Erode', districtId: 526 },
    { id: 181, name: 'Vellore', districtId: 553 },
    { id: 182, name: 'Thoothukudi', districtId: 546 },
    { id: 183, name: 'Dindigul', districtId: 525 },
    { id: 184, name: 'Thanjavur', districtId: 544 },
    { id: 185, name: 'Ranipet', districtId: 540 },
    { id: 186, name: 'Sivakasi', districtId: 555 },
    { id: 187, name: 'Karur', districtId: 530 },
    { id: 188, name: 'Nagercoil', districtId: 529 },
    { id: 189, name: 'Kanchipuram', districtId: 528 },
    { id: 190, name: 'Kumbakonam', districtId: 544 },
    { id: 191, name: 'Cuddalore', districtId: 523 },

    // Telangana
    { id: 192, name: 'Hyderabad', districtId: 559 },
    { id: 193, name: 'Warangal', districtId: 587 },
    { id: 194, name: 'Nizamabad', districtId: 578 },
    { id: 195, name: 'Karimnagar', districtId: 565 },
    { id: 196, name: 'Khammam', districtId: 566 },
    { id: 197, name: 'Ramagundam', districtId: 570 },
    { id: 198, name: 'Mahbubnagar', districtId: 569 },
    { id: 199, name: 'Nalgonda', districtId: 575 },
    { id: 200, name: 'Adilabad', districtId: 556 },
    { id: 201, name: 'Suryapet', districtId: 584 },
    { id: 202, name: 'Siddipet', districtId: 583 },
    { id: 203, name: 'Miryalaguda', districtId: 575 },

    // Tripura
    { id: 204, name: 'Agartala', districtId: 596 },

    // Uttar Pradesh
    { id: 205, name: 'Lucknow', districtId: 645 },
    { id: 206, name: 'Kanpur', districtId: 639 },
    { id: 207, name: 'Agra', districtId: 597 },
    { id: 208, name: 'Varanasi', districtId: 671 },
    { id: 209, name: 'Ghaziabad', districtId: 626 },
    { id: 210, name: 'Noida', districtId: 625 },
    { id: 211, name: 'Meerut', districtId: 651 },
    { id: 212, name: 'Prayagraj', districtId: 657 },
    { id: 213, name: 'Bareilly', districtId: 612 },
    { id: 214, name: 'Aligarh', districtId: 598 },
    { id: 215, name: 'Moradabad', districtId: 653 },
    { id: 216, name: 'Gorakhpur', districtId: 629 },
    { id: 217, name: 'Saharanpur', districtId: 660 },
    { id: 218, name: 'Jhansi', districtId: 636 },
    { id: 219, name: 'Firozabad', districtId: 624 },
    { id: 220, name: 'Muzaffarnagar', districtId: 654 },
    { id: 221, name: 'Mathura', districtId: 649 },

    // Uttarakhand
    { id: 222, name: 'Dehradun', districtId: 676 },
    { id: 223, name: 'Haridwar', districtId: 677 },
    { id: 224, name: 'Rishikesh', districtId: 676 },
    { id: 225, name: 'Haldwani', districtId: 683 },
    { id: 226, name: 'Roorkee', districtId: 677 },
    { id: 227, name: 'Nainital', districtId: 678 },

    // West Bengal
    { id: 228, name: 'Kolkata', districtId: 696 },
    { id: 229, name: 'Howrah', districtId: 692 },
    { id: 230, name: 'Durgapur', districtId: 701 },
    { id: 231, name: 'Asansol', districtId: 701 },
    { id: 232, name: 'Siliguri', districtId: 690 },
    { id: 233, name: 'Bardhaman', districtId: 703 },
    { id: 234, name: 'Malda', districtId: 697 },
    { id: 235, name: 'Krishnanagar', districtId: 699 },
    { id: 236, name: 'Balurghat', districtId: 689 },
    { id: 237, name: 'Jalpaiguri', districtId: 693 },

    // Andaman and Nicobar
    { id: 238, name: 'Port Blair', districtId: 710 },

    // Chandigarh
    { id: 239, name: 'Chandigarh', districtId: 711 },

    // Daman and Diu
    { id: 240, name: 'Daman', districtId: 713 },
    { id: 241, name: 'Diu', districtId: 714 },

    // Delhi
    { id: 242, name: 'New Delhi', districtId: 717 },
    { id: 243, name: 'Dwarka', districtId: 724 },
    { id: 244, name: 'Rohini', districtId: 720 },
    { id: 245, name: 'Saket', districtId: 722 },

    // Jammu and Kashmir
    { id: 246, name: 'Srinagar', districtId: 744 },
    { id: 247, name: 'Jammu', districtId: 732 },
    { id: 248, name: 'Anantnag', districtId: 726 },
    { id: 249, name: 'Baramulla', districtId: 728 },
    { id: 250, name: 'Kathua', districtId: 733 },

    // Ladakh
    { id: 251, name: 'Leh', districtId: 747 },
    { id: 252, name: 'Kargil', districtId: 746 },

    // Lakshadweep
    { id: 253, name: 'Kavaratti', districtId: 748 },

    // Puducherry
    { id: 254, name: 'Puducherry', districtId: 751 },
    { id: 255, name: 'Karaikal', districtId: 749 },
  ]

  for (const c of citiesData) {
    await prisma.city.upsert({
      where: { id: c.id },
      update: { name: c.name, districtId: c.districtId },
      create: c,
    })
  }
  console.log(`Seeded ${citiesData.length} explicit cities`)

  // Remove any auto-created cities from prior runs (ids > 255)
  await prisma.city.deleteMany({ where: { id: { gt: 255 } } })

  // Sync auto-increment sequence with the max remaining ID
  await prisma.$executeRawUnsafe(`SELECT setval('cities_id_seq', (SELECT COALESCE(MAX(id), 0) FROM cities))`)

  // Auto-create fallback city for every district that has no cities
  const districtIdsWithCities = await prisma.city.findMany({
    select: { districtId: true },
    distinct: ['districtId'],
  })
  const coveredDistrictIds = new Set(districtIdsWithCities.map(c => c.districtId))
  const allDistricts = await prisma.district.findMany({ select: { id: true, name: true } })
  let fallbackCount = 0
  for (const d of allDistricts) {
    if (!coveredDistrictIds.has(d.id)) {
      await prisma.city.create({ data: { name: d.name, districtId: d.id } })
      fallbackCount++
    }
  }
  if (fallbackCount > 0) {
    console.log(`Auto-created ${fallbackCount} fallback cities for districts with no cities`)
  }
}

main()
  .catch(e => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())
