import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const universities = [
  'Anna University',
  'University of Madras',
  'Bharathiar University',
  'Bharathidasan University',
  'Madurai Kamaraj University',
  'Tamil Nadu Agricultural University',
  'Tamil Nadu Dr. Ambedkar Law University',
  'Tamil Nadu Dr. M.G.R. Medical University',
  'Tamil Nadu Open University',
  'Tamil Nadu Physical Education and Sports University',
  'Tamil Nadu Teachers Education University',
  'Tamil University',
  'Mother Teresa Women\'s University',
  'Periyar University',
  'Thiruvalluvar University',
  'Alagappa University',
  'Annamalai University',
  'Manonmaniam Sundaranar University',
  'University of Calicut',
  'University of Kerala',
  'University of Mysore',
  'Bangalore University',
  'Osmania University',
  'University of Hyderabad',
  'University of Delhi',
  'Jawaharlal Nehru University',
  'University of Mumbai',
  'University of Calcutta',
  'University of Pune',
  'Savitribai Phule Pune University',
  'Gujarat University',
  'Panjab University',
  'University of Rajasthan',
  'Banaras Hindu University',
  'Aligarh Muslim University',
  'University of Allahabad',
  'University of Lucknow',
  'Dr. Ram Manohar Lohia Avadh University',
  'Chaudhary Charan Singh University',
  'Mahatma Gandhi Kashi Vidyapith',
  'University of Burdwan',
  'North Bengal University',
  'Sidho Kanho Birsha University',
  'West Bengal State University',
  'Dibrugarh University',
  'Gauhati University',
  'Nagaland University',
  'North-Eastern Hill University',
  'Tezpur University',
  'Tripura University',
  'Hemwati Nandan Bahuguna Garhwal University',
  'Kumaun University',
  'Uttarakhand Technical University',
  'University of Jammu',
  'University of Kashmir',
  'Sri Venkateswara University',
  'Acharya Nagarjuna University',
  'Andhra University',
  'Sri Krishna Devaraya University',
  'Kakatiya University',
  'Pondicherry University',
]

const colleges = [
  // Chennai
  'Indian Institute of Technology Madras',
  'College of Engineering, Guindy',
  'Madras Medical College',
  'Sri Ramachandra Institute of Higher Education and Research',
  'SRM Institute of Science and Technology',
  'Vellore Institute of Technology',
  'SSN College of Engineering',
  'Stella Maris College',
  'Loyola College',
  'Madras Christian College',
  'Women\'s Christian College',
  'Ethiraj College for Women',
  'M.O.P. Vaishnav College for Women',
  'Velammal Engineering College',
  'Rajalakshmi Engineering College',
  'Panimalar Engineering College',
  'Jeppiaar Engineering College',
  'Saveetha Engineering College',
  'Meenakshi College of Engineering',
  'R.M.K. Engineering College',
  'R.M.D. Engineering College',
  'Sri Venkateswara College of Engineering',
  'Easwari Engineering College',
  'Agni College of Technology',
  'St. Joseph\'s College of Engineering',
  'B.S. Abdur Rahman Crescent Institute of Science and Technology',
  'Hindustan Institute of Technology and Science',
  'Sathyabama Institute of Science and Technology',
  'MGR Educational and Research Institute',
  'Bharath Institute of Higher Education and Research',
  'Chennai Mathematical Institute',

  // Coimbatore
  'Coimbatore Institute of Technology',
  'Government College of Technology, Coimbatore',
  'PSG College of Technology',
  'PSG Institute of Medical Sciences and Research',
  'Amrita School of Engineering, Coimbatore',
  'Kumaraguru College of Technology',
  'Sri Krishna College of Engineering and Technology',
  'SNS College of Technology',
  'Dr. Mahalingam College of Engineering and Technology',
  'Karpagam College of Engineering',
  'Bannari Amman Institute of Technology',

  // Madurai
  'Thiagarajar College of Engineering',
  'Madurai Medical College',
  'Lady Doak College',
  'The American College',
  'Fatima College',
  'Sourashtra College',
  'Madurai Institute of Social Sciences',

  // Trichy
  'National Institute of Technology, Tiruchirappalli',
  'Indian Institute of Management Tiruchirappalli',
  'Bishop Heber College',
  'St. Joseph\'s College, Tiruchirappalli',
  'Holy Cross College, Tiruchirappalli',
  'Saranathan College of Engineering',
  'M.A.M. College of Engineering',

  // Salem
  'Government College of Engineering, Salem',
  'Sonaware college of Engineering',
  'Vinayaka Mission\'s Kirupananda Variyar Engineering College',
  'Mahendra Engineering College',
  'The Kavery College of Engineering',

  // Tirunelveli
  'Government College of Engineering, Tirunelveli',
  'St. Xavier\'s College, Palayamkottai',
  'Sarah Tucker College',
  'Manonmaniam Sundaranar University College',

  // Other TN cities
  'Government College of Engineering, Erode',
  'Government College of Engineering, Thanjavur',
  'Government College of Engineering, Bodinayakkanur',
  'Government Arts and Science College, Nagercoil',
  'Scott Christian College, Nagercoil',
  'Malankara Catholic College',
  'St. John\'s College, Palayamkottai',
  'Arul Anandar College, Madurai',
  'Vivekananda College, Kanyakumari',
  'Sree Narayana College, Kollam',
  'M.V. Muthiah Government Arts College, Dindigul',
  'Government Arts College, Coimbatore',
  'Government Arts College, Salem',
  'Ayya Nadar Janaki Ammal College, Sivakasi',
  'Sri S. Ramasamy Naidu Memorial College, Sattur',
  'V.H.N.S.N. College, Virudhunagar',
  'P.S.R. Arts and Science College, Sivakasi',
  'S. Veerasamy Chettiar College of Arts and Sciences',
  'Rani Anna Government College for Women, Tirunelveli',
  'Government Arts College, Karur',
  'A.V.V.M. Sri Pushpam College, Thanjavur',
  'Government Arts and Science College, Cuddalore',
  'Government Arts and Science College, Villupuram',
  'Kamban College of Arts and Science',
  'Government Arts College, Dharmapuri',
  'Government Arts College, Krishnagiri',
  'Government Arts College, Ooty',
  'A.V.S. College of Arts and Science',
  'Government Arts and Science College, Kumbakonam',
  'Government Arts and Science College, Nagapattinam',
  'Government Arts and Science College, Pudukkottai',
  'Government Arts and Science College, Ramanathapuram',
  'Government Arts and Science College, Sivaganga',
  'Government Arts and Science College, Theni',
  'Government Arts and Science College, Tirupathur',
  'Government Arts and Science College, Ariyalur',
  'Government Arts and Science College, Kallakurichi',
  'Government Arts and Science College, Ranipet',
  'Government Arts and Science College, Tenkasi',
  'Government Arts and Science College, Chengalpattu',
  'Government Arts and Science College, Mayiladuthurai',
]

async function main() {
  for (const name of universities) {
    await prisma.university.upsert({
      where: { name },
      update: { status: 'approved' },
      create: { name, status: 'approved' },
    })
  }
  console.log(`Seeded ${universities.length} universities`)

  for (const name of colleges) {
    await prisma.college.upsert({
      where: { name },
      update: { status: 'approved' },
      create: { name, status: 'approved' },
    })
  }
  console.log(`Seeded ${colleges.length} colleges`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
